name: build
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
    steps:
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt-openj9
          java-version: 11
      - name: Checkout Frege Gradle Plugin Repo
        uses: actions/checkout@v2
        with:
          repository: tricktron/frege-gradle-plugin
          ref: v2.0.1-alpha
          path: frege-gradle-plugin
      - name: Install Frege Gradle Plugin to MavenLocal
        run: |
          cd frege-gradle-plugin
          if [ "$RUNNER_OS" = "Windows" ]; then
            ./gradlew.bat clean publishToMavenLocal
          else
            ./gradlew clean publishToMavenLocal
          fi
        shell: bash
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: frege-lsp-server
      - name: Run Unit Tests
        run: |
          cd frege-lsp-server
          if [ "$RUNNER_OS" = "Windows" ]; then
            ./gradlew.bat clean check
          else
            ./gradlew clean check
          fi
        shell: bash
